# ---- PROD Profile: PostgreSQL (Render) ----
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

# ---- Prod optimisations ----
spring.thymeleaf.cache=true
logging.level.com.bgc=WARN
spring.h2.console.enabled=false
