# ---- PROD Profile: PostgreSQL ----
spring.datasource.url=jdbc:postgresql://localhost:5432/bgceventdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:bgcuser}
spring.datasource.password=${DB_PASSWORD:bgcpassword}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

spring.h2.console.enabled=false
