-- ================================================
-- V11 — BCC Offices table + link users to office
-- Author: NTAGANIRA Heritier | 2026-02-27
-- ================================================

CREATE TABLE IF NOT EXISTS bcc_offices (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(20)  NOT NULL UNIQUE,
    name         VARCHAR(150) NOT NULL,
    country      VARCHAR(100) NOT NULL,
    city         VARCHAR(100) NOT NULL,
    address      VARCHAR(255),
    phone        VARCHAR(50),
    email        VARCHAR(150),
    head_of_office VARCHAR(150),
    active       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_offices_code    ON bcc_offices(code);
CREATE INDEX idx_offices_country ON bcc_offices(country);

-- Link users to an office (nullable — existing users keep branch string)
ALTER TABLE users ADD COLUMN office_id BIGINT;
ALTER TABLE users ADD CONSTRAINT fk_users_office
    FOREIGN KEY (office_id) REFERENCES bcc_offices(id) ON DELETE SET NULL;

-- Add a new permission for office management
INSERT INTO permissions (name, description)
VALUES ('MANAGE_OFFICES', 'Create, edit and delete BCC offices');

-- Grant MANAGE_OFFICES to ROLE_ADMIN
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r JOIN permissions p
ON r.name = 'ROLE_ADMIN' AND p.name = 'MANAGE_OFFICES';

-- Seed representative BCC offices
INSERT INTO bcc_offices (code, name, country, city, address, phone, email, head_of_office) VALUES
('HQ',      'BCC Headquarters',          'Rwanda',      'Kigali',        'KG 7 Ave, Kigali',              '+250 788 000 001', 'hq@bgc.rw',      'Dr. Jean Ndagijimana'),
('NBI',     'BCC Nairobi Office',         'Kenya',       'Nairobi',       'Upper Hill, Nairobi',           '+254 20 000 001',  'nairobi@bgc.rw', 'Alice Wanjiru'),
('DAR',     'BCC Dar es Salaam Office',   'Tanzania',    'Dar es Salaam', 'Samora Ave, Dar es Salaam',     '+255 22 000 001',  'dar@bgc.rw',     'Robert Mwangi'),
('KMP',     'BCC Kampala Office',         'Uganda',      'Kampala',       'Kampala Rd, Kampala',           '+256 41 000 001',  'kampala@bgc.rw', 'Sarah Nakato'),
('LGS',     'BCC Lagos Office',           'Nigeria',     'Lagos',         'Victoria Island, Lagos',        '+234 1 000 001',   'lagos@bgc.rw',   'Emmanuel Okafor'),
('ACC',     'BCC Accra Office',           'Ghana',       'Accra',         'Airport City, Accra',           '+233 30 000 001',  'accra@bgc.rw',   'Kwame Mensah'),
('JHB',     'BCC Johannesburg Office',    'South Africa','Johannesburg',  'Sandton, Johannesburg',         '+27 11 000 001',   'jhb@bgc.rw',     'Naledi Dlamini'),
('ADD',     'BCC Addis Ababa Office',     'Ethiopia',    'Addis Ababa',   'Bole Sub-City, Addis Ababa',    '+251 11 000 001',  'addis@bgc.rw',   'Tigist Haile'),
('WDC',     'BCC Washington D.C. Office', 'USA',         'Washington DC', '1600 K Street NW, Washington',  '+1 202 000 001',   'dc@bgc.rw',      'Linda Thompson');
