-- V14: Event participants — links users to events with a role (PREACHER, MC, SPEAKER, WORSHIP…)
-- Drop the simple string columns added in V12 (replaced by proper relation)
ALTER TABLE events DROP COLUMN IF EXISTS preacher;
ALTER TABLE events DROP COLUMN IF EXISTS mc;

CREATE TABLE event_participants (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    BIGINT       NOT NULL,
    user_id     BIGINT       NOT NULL,
    role        VARCHAR(50)  NOT NULL,   -- PREACHER | MC | SPEAKER | WORSHIP | OTHER
    note        VARCHAR(255),
    CONSTRAINT fk_ep_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
    CONSTRAINT fk_ep_user  FOREIGN KEY (user_id)  REFERENCES users(id)  ON DELETE CASCADE,
    CONSTRAINT uq_ep       UNIQUE (event_id, user_id, role)
);
