-- V3__add_permissions_table.sql
CREATE TABLE IF NOT EXISTS permissions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255)
);
